# Generated by Django 5.0 on 2023-12-26 17:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_employee_sector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('company', 'user')},
        ),
    ]
