# Generated by Django 5.0 on 2023-12-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_employee_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='sector',
            field=models.ManyToManyField(blank=True, to='members.sector'),
        ),
    ]
